### ISSUE TITLE
Run privileged container in Fogify

### ISSUE THREAD

**Issue by tommazzo89** [UCY-LINC-LAB/fogify#1]
Hi,

This is a really great project!

I'm trying to run a Kubernetes cluster in Fogify. For this purpose, I've set up a docker-compose file and shell scripts (see [here](https://gitlab.com/rainbow-project1/rainbow-scheduler/-/tree/master/hack/k8s-test-cluster)) that initialize a Kubernetes cluster using the Docker images and bootstrapping procedure from the [kind](https://kind.sigs.k8s.io) project. Running the cluster with docker-compose works, but with Fogify, the containers keep crashing, because they are not executed in privileged mode.

Steps to reproduce the problem:

1. Build the Docker image from [here](https://gitlab.com/rainbow-project1/rainbow-scheduler/-/tree/master/hack/k8s-test-cluster)
2. Run the docker-compose file from [here](https://gitlab.com/rainbow-project1/rainbow-scheduler/-/tree/master/hack/k8s-test-cluster/fogify-k8s) in Fogify.
3. List all containers using `docker ps --all`
4. Get the logs for one of the crashed `control-plane` container. They will contain the following:
```
WARN: /dev/kmsg does not exist, nor does /dev/console!
INFO: ensuring we can execute mount/umount even with userns-remap
INFO: remounting /sys read-only
mount: /sys: permission denied.
```

Using a docker-compose file with just the kind [base image](https://kind.sigs.k8s.io/docs/design/base-image/) should allow reproducing the problem as well. When using this option, it is important that the container is configured with the following options:
```
volumes:
  # Ensures that pods, logs etc. are not on the container filesystem.
  - "/var"
  # Some K8s things want to read /lib/modules.
  - "/lib/modules:/lib/modules:ro"
tmpfs:
  - "/tmp" # various things depend on working /tmp
  - "/run" # systemd wants a writable /run
privileged: true
security_opt:
  - "seccomp=unconfined"
  - "apparmor=unconfined"
```

**Comment by MosesSymeonidis** [comment]
Hi, 

This problem occurs due to the limited capabilities of the docker swarm (the initial docker orchestrator of Fogify).
To overcome this issue, we extended Fogify and introduced docker-compose as an extra single-host container orchestrator.
You will find more information and examples at https://github.com/UCY-LINC-LAB/fogify/tree/master/examples/kind-project 

Thank you
